/*
 * Autori:
 * - Federico Barbotti, 752545, Varese
 * - Oittijo Ahemmed Sarkar, 759646, Varese
 * - Bennajim Alì, 760125, Varese
 */
/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package dev.theknife.app;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

/**
 * Test suite per la classe principale {@link App}.
 * <p>
 * Verifica l'istanziazione corretta dell'applicazione JavaFX.
 * </p>
 *
 * @author Federico Barbotti, Oittijo Ahemmed Sarkar, Bennajim Alì
 * @version 1.0
 * @since 1.0
 */
class AppTest {
    @Test void appCanBeCreated() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest, "app should be created");
    }
}
