name: The Knife CI

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 24
        uses: actions/setup-java@v4
        with:
          java-version: '24'
          distribution: 'temurin'

      - name: Ensure gradlew is executable
        run: chmod +x gradlew

      - name: Setup Gradle with caching
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: wrapper

      - name: Run tests
        run: ./gradlew test --parallel --max-workers=2

      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-results
          path: app/build/reports/tests/

  build-jar:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 24
        uses: actions/setup-java@v4
        with:
          java-version: '24'
          distribution: 'temurin'

      - name: Ensure gradlew is executable
        run: chmod +x gradlew

      - name: Setup Gradle (no cache issues)
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: wrapper
          cache-disabled: true  # disable until cache service is stable

      - name: Build JAR
        run: ./gradlew jar --parallel --max-workers=2

      - name: List build output
        run: ls -la app/build/libs/ || true

      - name: Upload runnable JAR
        uses: actions/upload-artifact@v4
        with:
          name: TheKnife-app
          path: app/build/libs/TheKnife.jar
